# default database
default: 
  type: mysql
  server: db
  user: root
  password: root_password
  database: your_database_name

# second database, for example for user management
usermanagement: 
  type: mysql
  server: db
  user: root
  password: root_password
  database: your_second_database_name

# sample for sql server connection
#sqlserverdb: 
#  type: sqlsrv
#  server: your_sql_server_address
#  user: your_sql_server_username
#  password: your_sql_server_password
#  database: your_sql_server_database_name